#runtime: java11
#instance_class: F1
service: accounts
runtime: java
env: flex
runtime_config:
  jdk: openjdk8

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

#env_variables:
#  SPRING_PROFILES_ACTIVE: "gcp"
#handlers:
#  - url: /.*
#    script: this field is required, but ignored
#manual_scaling:
#  instances: 1
#resources:
#  cpu: 1
#  memory_gb: 1
#  disk_size_gb: 1