server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://staging.omni-trade.xyz:3306/account_service_db?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: uXxck2LbP!bTE^2_
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

bs:
  mysql:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://staging.omni-trade.xyz:3306/account_service_db?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: uXxck2LbP!bTE^2_
    pool:
      name: order-mysql

management:
  endpoints:
    web:
      exposure:
        include: "*"