server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key: <ask vincent for key>
      secret-key: <ask vincent for key>
    region:
      static: ap-southeast-2
      auto: false
    end-point:
      buyer:
        uri: https://sqs.ap-southeast-2.amazonaws.com/099209825265/order_matching_buyer_queue.fifo
      seller:
        uri: https://sqs.ap-southeast-2.amazonaws.com/099209825265/order_matching_seller_queue.fifo

bs:
  mysql:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.32.176.3:3306/order_matching_service_db?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: ordermatching
    password: Team3$
    pool:
      name: order-mysql