server:
  port: 8080

spring:
  profiles:
    active: @activatedProperties@

cloud:
  aws:
    credentials:
      access-key: x
      secret-key: x
    region:
      static: ap-southeast-2
      auto: false
    end-point:
      buyer:
        uri: http://127.0.0.1:9324/099209825265/order_matching_buyer_queue.fifo
      seller:
        uri: http://127.0.0.1:9324/099209825265/order_matching_seller_queue.fifo

bs:
  mysql:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/omnitrade_orders?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: Team3$
    pool:
      name: order-mysql

management:
  endpoints:
    web:
      exposure:
        include: "*"
