name: Deploy to Production
on:
  push:
    branches:
      - production
      - github-actions

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
    - id: 'checkout'
    - uses: 'actions/checkout@v3'

    - name: Authenticate
    - id: 'auth'
    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Deploy to App Engine
    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'

    - name: Verify deployment
    - id: 'verify'
      run: 'curl "${{ steps.deploy.outputs.url }}"'