name: Deploy to Production
on:
  push:
    branches:
      - production
      - github-actions

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    # NOTE Maven and GCloud SDK CLI are pre-installed on Github-hosted runners
    # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software for details
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Build and deploy
        run: "mvn clean package appengine:deploy"